//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace haber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int YorumId { get; set; }
        public string Yorum1 { get; set; }
        public Nullable<int> Kullanici { get; set; }
        public string Puan { get; set; }
        public Nullable<int> HaberId { get; set; }
    
        public virtual Haber Haber { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
    }
}
